name: cursor_chat_cli
description: A CLI tool for browsing and extracting Cursor chat histories
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  sqlite3: ^2.1.0
  dart_console: ^1.2.0
  path_provider: ^2.1.1
  intl: ^0.18.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0 